### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by hyperupcall** [dragonman225/jade#1]
Thank you for making Jade, I really like many ideas it brings to the table, like the simple user interface, and how blocks are really easy to use and draw connections between.

I notice the readme says:

> Since I've moved on to a new project, [tableOS](https://tableos.substack.com/p/alpha), and am no longer developing Jade, I want to share the code publicly, for anyone interested to study the technology and concepts.
>
> The code is neither guaranteed to run, nor will I provide direct support. But if you have questions about how something works or are interested in the UI design, feel free to open issues, I will consider writing posts to talk about them.

I am quite interested in looking at the code to see the technology and concepts, but the only thing that is holding me back is the lack of a license. I'm probably going to be modifying some code or possibly integrating this project with some other knowledge or note-taking projects of mine. Nothing big or anything, just personal stuff, but it would be nice to have some common license in this repository that allows the usual stuff.

**Comment by dragonman225** [comment]
Thank you for being interested in Jade!

My motivation of publishing the code is to allow people who want to build features that's demonstrated in Jade to learn how it works more easily by following the code, instead of figuring it out from scratch.

I don't recommend that you copy any of Jade's code or integrate any module with other projects without understanding it first, since the code is not maintained and may be obsolete. For example, it's not using today's common practices or it doesn't work with latest versions of dependencies.

You can re-implement features using the same concepts. I think if you can explain your implementation with common lower-layer knowledge, such as published algorithms, software design patterns, or another open-source library's API, you can do whatever you want with no strings attached.

I'd like to encourage people to understand the technology rather than blindly reuse the half-baked code and find it not working. I couldn't find a proper license for this scenario so I left it undecided.

By the way, if you have difficulty in understanding something in the codebase, let me know by opening an issue per topic you need guidance.

**Comment by hyperupcall** [comment]
Thank you for your detailed response - I appreciate that you have published the code to jade and I think encouraging understanding rather than blind reuse is a noble goal. However, I disagree with your action of excluding a license as a sort of enforcement mechanism to achieve this goal - that is how I see it at least.

As far as I understand it, the code is still under exclusive copyright. According to [GitHub](https://opensource.guide/legal/#why-do-people-care-so-much-about-the-legal-side-of-open-source):

> In general, that means nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

Although I appreciate your intentions from an emotional standpoint, I feel unfomfortable from a legal standpoint. It helps that you have specified conditions under which we can "do whatever we want" with the code in writing, but to me, it would seem like a high bar, legally speaking.

Even cases in which I read the code, and I either (1) take inspiration from them or (2) reuse the code directly while completely understanding it, it is an unecessary risk I do not wish to take, however low the probability of litigation, arbitration, mediation, or what have you. I simply cannot be confident I am fully complying, or will be able to show so, with your bespoke terms - because I am not a lawyer.

Perhaps this sounds silly, but maybe that's because different prople have diverent aversions to different risks. I'll still take inspiration from jade, from its user interface rather than the underlying code. I'm sure some people won't think too much about the license and that's OK for them, but for me, I'll be choosing not to look at the code until some "common" license is added.

**Comment by dragonman225** [comment]
Thank you for pointing out GitHub's guide about licensing!

Then, from the words of the guide, my understanding is that Jade's codebase is still proprietary, and nobody can make use of the code at this moment from the legal perspective.

I understand your choice of respecting the copyright, which is reasonable and responsible. I'll look into licensing more and update here whenever new decisions are made.

**Comment by dragonman225** [comment]
Added Apache 2.0 open source license.
